@extends('templates.app')

@section('pageTitle', "Terms of Service - ")

@section('additional_headers')
    <link rel="stylesheet" href="{{ asset('css/acknowledgement.css') }}"/>
@endsection

@section('content')
    <section id="news">
        <div class="container-fluid">
            <div class="row h-100 justify-content-center align-items-center">
                <!--<h1 class="animated fadeIn">Did you notice the page transition?</h1>-->
                <div class="container animated fadeInUp faster">
                    <div class="news-header align-items-center d-flex">
                        <a href="#back" class="d-flex">
                            <i class="material-icons">keyboard_backspace</i>
                            <h5>Return</h5>
                        </a>
                    </div>

                    <div class="news-title justify-content-center">
                        <div class="col-12">
                            <h1>Terms of Service</h1>
                            <div class="news-info d-flex justify-content-center">
                                <h2>December 12th by </h2>
                                <h2 class="news-author">Ascension</h2>
                            </div>
                        </div>
                    </div>


                    <div class="news-content justify-content-center align-items-center">
                        <h4>Terms of Use</h4>
                        <p>BY ACCESSING OR USING WWW.PROJECT-ASCENSION.COM (THE "SITE") AND ITS SERVICES (THE
                            "SERVICES"), YOU (THE "USER") AGREE TO COMPLY WITH THE TERMS AND CONDITIONS GOVERNING THE
                            USER'S USE OF ANY AREAS OF THE SITE AND AFFILIATED SERVICES AS SET FORTH BELOW.</p>

                        <h5>USE OF SITE</h5>
                        <p>THIS SITE OR ANY PORTION OF THE SITE AS WELL AS THE SERVICES MAY NOT BE REPRODUCED,
                            DUPLICATED, COPIED, SOLD, RESOLD, OR OTHERWISE EXPLOITED FOR ANY COMMERCIAL PURPOSE EXCEPT
                            AS EXPRESSLY PERMITTED BY PROJECT-ASCENSION.COM. PROJECT-ASCENSION RESERVES THE RIGHT TO
                            REFUSE SERVICE IN ITS DISCRETION, WITHOUT LIMITATION, IF PROJECT-ASCENSION BELIEVES THE USER
                            CONDUCT VIOLATES APPLICABLE LAW OR IS HARMFUL TO THE INTERESTS OF PROJECT-ASCENSION, OTHER
                            USERS OF THE SITE AND THE SERVICES OR ITS AFFILIATES.</p>

                        <h5>USE OF SERVICES</h5>
                        <p>PROJECT-ASCENSION.COM IS A NON-PROFIT PROJECT DEVELOPED TO IMITATE OUTDATED GAME VERSIONS FOR
                            EDUCATIONAL PURPOSES ONLY. THE SITE AND THE SERVICES DO NOT SUPPORT AND DO NOT PROVIDE ANY
                            MODIFICATION TO GAME FILES. BY USING THE SITE OR THE SERVICES, THE USER AGREES TO TAKE
                            RESPONSIBILITY TO FOLLOW GAME’S EULA.</p>

                        <h5>AGE RESTRICTIONS ON USE OF OUR WEBSITE</h5>
                        <p>OUR WEBSITE AND ANY PRODUCTS OR SERVICES AVAILABLE ON OR VIA THE WESBITES ARE NOT INTENDED
                            FOR USE BY INDIVIDUALS UNDER THE AGE OF 18.</p>
                        <p>IF YOU ARE UNDER THE AGE OF 18, YOU MUST NOT USE OUR WEBSITE, PURCHASE OR ATTEMPT TO PURCHASE
                            ANY OF OUR PRODUCTS OR SERVICES, OR SUBMIT ANY PERSONAL INFORMATION TO US.</p>
                        <p>WE DO NOT KNOWINGLY OR INTENTIONALLY PROCESS THE PERSONAL INFORMATION OF ANY INDIVIDUAL UNDER
                            THE AGE OF 18.</p>

                        <h5>DISTRIBUTION</h5>
                        <p>PROJECT-ASCENSION.COM DOES NOT SUPPORT DISTRIBUTION OF ANY GAME CLIENTS. DOWNLOAD LINKS ON
                            THE SITE CONSTITUTE MIRRORS OF EXTERNAL SITES FOR EDUCATIONAL PURPOSES.</p>

                        <h5>SITE ACCOUNT</h5>
                        <p>THE USER MAY REGISTER A REGULAR ACCOUNT AND PASSWORD FOR THE SERVICE FOR FREE. YOU ARE
                            RESPONSIBLE FOR ALL ACTIVITY UNDER YOUR ACCOUNT, ASSOCIATED ACCOUNTS, AND PASSWORDS. THE
                            SITE IS NOT RESPONSIBLE FOR UNAUTHORISED ACCESS TO YOUR ACCOUNT, AND ANY LOSS OF VIRTUAL
                            ITEMS ASSOCIATED WITH IT.</p>

                        <h5>EVENTS, VIDEOS AND COMMUNITY CREATIONS</h5>
                        <p>UPON REGISTERING AN ACCOUNT, YOU AGREE THAT YOUR ACCOUNT OR CHARACTERS MAY BE INCLUDED IN ANY
                            EVENTS, STREAMS OR VIDEOS FOR PROMOTION OR REVIEW PURPOSES.</p>

                        <h5>ACCESS TO THE SITE AND SERVICES</h5>
                        <p>PROJECT-ASCENSION PROVIDES FREE AND UNLIMITED ACCESS TO THE SITE AND THE SERVICES.</p>

                        <h5>SUBMISSION</h5>
                        <p>PROJECT-ASCENSION DOES NOT ASSUME ANY OBLIGATION WITH RESPECT TO ANY SUBMISSION AND NO
                            CONFIDENTIAL OR FIDUCIARY UNDERSTANDING OR RELATIONSHIP IS ESTABLISHED BY THE SITE'S RECEIPT
                            OR ACCEPTANCE OF ANY SUBMISSION. ALL SUBMISSIONS BECOME THE EXCLUSIVE PROPERTY OF THE SITE
                            AND ITS AFFILIATES. THE SITE AND ITS AFFILIATES MAY USE ANY SUBMISSION WITHOUT RESTRICTION
                            AND THE USER SHALL NOT BE ENTITLED TO ANY COMPENSATION.</p>

                        <h5>THIRD-PARTY CONTENT</h5>
                        <p>NEITHER PROJECT-ASCENSION, NOR ITS AFFILIATES, NOR ANY OF THEIR RESPECTIVE OFFICERS,
                            DIRECTORS, EMPLOYEES, OR AGENTS, NOR ANY THIRD PARTY, INCLUDING ANY PROVIDER/AFFILIATE, OR
                            ANY OTHER USER OF THE SITE AND SERVICES, GUARANTEES THE ACCURACY, COMPLETENESS, OR
                            USEFULNESS OF ANY CONTENT, NOR ITS MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE. IN
                            SOME INSTANCES, THE CONTENT AVAILABLE THROUGH THE SITE MAY REPRESENT THE OPINIONS AND
                            JUDGMENTS OF PROVIDERS/AFFILIATES OR USERS. PROJECT-ASCENSION AND ITS AFFILIATES DO NOT
                            ENDORSE AND SHALL NOT BE RESPONSIBLE FOR THE ACCURACY OR RELIABILITY OF ANY OPINION, ADVICE,
                            OR STATEMENT MADE ON THE SITE AND THE SERVICES BY ANYONE OTHER THAN AUTHORISED
                            PROJECT-ASCENSION EMPLOYEES. UNDER NO CIRCUMSTANCES SHALL PROJECT-ASCENSION, OR ITS
                            AFFILIATES, OR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE
                            FOR ANY LOSS, DAMAGE OR HARM CAUSED BY A USER'S RELIANCE ON INFORMATION OBTAINED THROUGH THE
                            SITE AND THE SERVICES. IT IS THE RESPONSIBILITY OF THE USER TO EVALUATE THE INFORMATION,
                            OPINION, ADVICE, OR OTHER CONTENT AVAILABLE THROUGH THIS SITE.</p>

                        <h5>DISCLAIMERS AND LIMITATION OF LIABILITY</h5>
                        <p>USER AGREES THAT USE OF THE SITE AND THE SERVICES IS AT THE USER'S SOLE RISK. NEITHER
                            PROJECT-ASCENSION, NOR ITS AFFILIATES, NOR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS,
                            EMPLOYEES, AGENTS, THIRD-PARTY CONTENT PROVIDERS, MERCHANTS, SPONSORS, LICENSORS OR THE LIKE
                            (COLLECTIVELY, "PROVIDERS"), WARRANT THAT THE SITE AND THE SERVICES WILL BE UNINTERRUPTED OR
                            ERROR-FREE; NOR DO THEY MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE
                            USE OF THE SITE AND THE SERVICES, OR AS TO THE ACCURACY, RELIABILITY, OR CURRENCY OF ANY
                            INFORMATION CONTENT, SERVICE, OR MERCHANDISE PROVIDED THROUGH THIS SITE. THE SITE AND THE
                            SERVICES ARE PROVIDED BY PROJECT-ASCENSION ON AN "AS IS" AND "AS AVAILABLE" BASIS. THE SITE
                            MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION
                            OF THE SITE, THE INFORMATION, CONTENT, MATERIALS OR PRODUCTS, INCLUDED ON THIS SITE. TO THE
                            FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, THE SITE DISCLAIMS ALL WARRANTIES, EXPRESS OR
                            IMPLIED, INCLUDING BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
                            A PARTICULAR PURPOSE. PROJECT-ASCENSION WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND
                            ARISING FROM THE USE OF THE SITE AND THE SERVICES, INCLUDING BUT NOT LIMITED TO DIRECT,
                            INDIRECT, INCIDENTAL, PUNITIVE AND CONSEQUENTIAL DAMAGES. UNDER NO CIRCUMSTANCES SHALL
                            PROJECT-ASCENSION OR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DISTRIBUTING THE
                            SITE AND THE SERVICES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, OR
                            CONSEQUENTIAL DAMAGES THAT RESULT FROM THE USE OF OR INABILITY TO USE THE SITE AND THE
                            SERVICES, INCLUDING BUT NOT LIMITED TO RELIANCE BY THE USER ON ANY INFORMATION OBTAINED FROM
                            THE SITE OR THAT RESULT FROM MISTAKES, OMISSIONS, INTERRUPTIONS, DELETION OF FILES OR EMAIL,
                            ERRORS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION, OR ANY FAILURE OF
                            PERFORMANCE, WHETHER OR NOT RESULTING FROM ACTS OF GOD, COMMUNICATIONS FAILURE, THEFT,
                            DESTRUCTION, OR UNAUTHORISED ACCESS TO THE SITE'S RECORDS, PROGRAMS, OR SERVICES. THE USER
                            HEREBY ACKNOWLEDGES THAT THESE DISCLAIMERS AND LIMITATION ON LIABILITY SHALL APPLY TO ALL
                            CONTENT, MERCHANDISE, AND SERVICES AVAILABLE THROUGH THE SITE AND THE SERVICES. IN STATES
                            THAT DO NOT ALLOW THE EXCLUSION OF LIMITATION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL
                            OR INCIDENTAL DAMAGES, THE USER AGREES THAT LIABILITY IN SUCH STATES SHALL BE LIMITED TO THE
                            FULLEST EXTENT PERMITTED BY APPLICABLE LAW.</p>

                        <h5>TERMINATION OF SERVICE</h5>
                        <p>PROJECT-ASCENSION RESERVES THE RIGHT, IN ITS SOLE DISCRETION, TO CHANGE, SUSPEND, LIMIT, OR
                            DISCONTINUE ANY ASPECT OF THE SERVICE AND THE SERVICES AT ANY TIME. PROJECT-ASCENSION MAY
                            SUSPEND OR TERMINATE ANY USER'S ACCESS TO ALL OR PART OF THE SITE AND THE SERVICES, WITHOUT
                            NOTICE, FOR ANY CONDUCT THAT PROJECT-ASCENSION, IN ITS SOLE DISCRETION, BELIEVES IS IN
                            VIOLATION OF THESE TERMS AND CONDITIONS.</p>

                        <h5>DONATIONS</h5>
                        <p>DONATIONS ARE MADE ON A VOLUNTARY BASIS IN APPRECIATION OF THE SITE AND THE SERVICES.
                            PROJECT-ASCENSION DOES NOT ASSUME ANY FINANCIAL OBLIGATION WITH RESPECT TO DONATIONS. THE
                            USER MUST BE OVER 18 TO BE ELIGIBLE TO MAKE A DONATION TO PROJECT-ASCENSION.
                            PROJECT-ASCENSION IS NOT LIABLE FOR ANY UNAUTHORIZED DONATIONS.</p>

                        <h5>ACKNOWLEDGEMENT</h5>
                        <p>BY ACCESSING OR USING THE SITE AND THE SERVICES, THE USER AGREES TO BE BOUND BY THESE TERMS
                            AND CONDITIONS, INCLUDING DISCLAIMERS. PROJECT-ASCENSION RESERVES THE RIGHT TO MAKE CHANGES
                            TO THE SITE AND THESE TERMS AND CONDITIONS, INCLUDING DISCLAIMERS, AT ANY TIME. IF YOU DO
                            NOT AGREE TO THE PROVISIONS OF THIS AGREEMENT OR ARE NOT SATISFIED WITH THE SERVICE, YOUR
                            SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE YOUR USE OF THE SERVICE.</p>

                        <h5>PRIVACY STATEMENT</h5>
                        <p>CERTAIN USER INFORMATION COLLECTED THROUGH THE USE OF THIS WEBSITE IS AUTOMATICALLY STORED
                            FOR REFERENCE. WE TRACK SUCH INFORMATION TO PERFORM INTERNAL RESEARCH ON OUR USERS'
                            DEMOGRAPHIC INTERESTS AND BEHAVIOUR AND TO BETTER UNDERSTAND, PROTECT AND SERVE OUR
                            COMMUNITY OF USERS. PAYMENT OR ANY OTHER FINANCIAL INFORMATION IS NEVER SUBMITTED, DISCLOSED
                            OR STORED ON THE SITE AND IS BOUND TO TERMS AND CONDITIONS AND PRIVACY POLICY OF OUR
                            RESPECTIVE PARTNERS AND/OR PAYMENT PROCESSORS. BASIC USER INFORMATION (SUCH AS IP ADDRESS,
                            LOGS FOR USING WEBSITE INTERFACE AND ACCOUNT MANAGEMENT) MAY BE DISCLOSED TO OUR PARTNERS IN
                            MUTUAL EFFORTS TO COUNTER POTENTIAL ILLEGAL ACTIVITIES. PROJECT-ASCENSION MAKES SIGNIFICANT
                            EFFORT TO PROTECT SUBMITTED INFORMATION TO PREVENT UNAUTHORISED ACCESS TO THAT INFORMATION
                            IN ITS INTERNAL PROCEDURES AND TECHNOLOGY. HOWEVER, WE DO NOT GUARANTEE, NOR SHOULD YOU
                            EXPECT, THAT YOUR PERSONAL INFORMATION AND PRIVATE COMMUNICATIONS WILL ALWAYS REMAIN
                            PRIVATE.</p>

                        <h5>CONTACTING US</h5>
                        <p>IF THERE ARE ANY QUESTIONS REGARDING THIS PRIVACY POLICY YOU MAY CONTACT US USING THE
                            INFORMATION BELOW.
                        <ul>
                            <li>www.project-ascension.com</li>
                            <li>help@project-ascension.com</li>
                        </ul>
                        </p>
                    </div>

                    <div class="news-footer align-items-center d-flex justify-content-center">
                        <a href="#top"><h5>Back to top</h5></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('additional_scripts')
    <script src="{{ asset('js/preloader.js') }}"></script>
    <script src="{{ asset('js/news/news-anim.js') }}"></script>
@endsection
